import Mathlib

/-!
# Conjecture 00000008869: naming `2` loses in Sylver coinage

In Sylver coinage two players alternately name positive integers. A number may not be named
if it is a sum of previously named numbers (a nonnegative integer combination of them), and
the player who names `1` loses. Conjecture 00000008869 claims that naming `2` is the first
player's winning first move, and that in the prime version (only primes and `1` may be named)
the winning first move is still exactly `2`.

Both claims fail. After the first player names `2`, the second player names `3`. Every
integer `n ≥ 2` is a sum of `2`s and `3`s, so the only number the first player may still name
is `1`, and naming it loses. The reply `3` is a prime, so the same happens in the prime
version.

Game values are defined inductively (`Outcome`): the player to move *wins* from a position if
some legal move other than `1` leads to a position the next player *loses*, and *loses* if
every legal move other than `1` leads to a position the next player wins. Winning and losing
are mutually exclusive (`not_win_and_lose`).
-/

namespace Submission00000008869

/-- `n` is a legal move after the numbers in `S` have been named: `n` is positive and not a
nonnegative integer combination of named numbers, i.e. not in the additive submonoid of `ℕ`
generated by `S`. -/
def Legal (S : Finset ℕ) (n : ℕ) : Prop :=
  0 < n ∧ n ∉ AddSubmonoid.closure (S : Set ℕ)

/-- Outcomes of Sylver coinage in which only numbers satisfying `allowed` may be named
(`allowed = fun _ => True` is the usual game; the prime version allows primes and `1`).
`Outcome allowed true S`: the player to move from `S` has a winning strategy.
`Outcome allowed false S`: the player to move from `S` loses against best play.
Naming `1` loses at once, so it is never a winning move. -/
inductive Outcome (allowed : ℕ → Prop) : Bool → Finset ℕ → Prop
  | win (S : Finset ℕ) (n : ℕ) : allowed n → Legal S n → n ≠ 1 →
      Outcome allowed false (insert n S) → Outcome allowed true S
  | lose (S : Finset ℕ) :
      (∀ n, allowed n → Legal S n → n ≠ 1 → Outcome allowed true (insert n S)) →
      Outcome allowed false S

/-- The usual game: every positive integer may be named. -/
def anyNumber : ℕ → Prop := fun _ => True

/-- The prime version: only primes and `1` may be named. -/
def primeOrOne : ℕ → Prop := fun n => n = 1 ∨ n.Prime

/-- A position cannot be both a win and a loss for the player to move. -/
theorem not_win_and_lose (allowed : ℕ → Prop) {b : Bool} {S : Finset ℕ}
    (h : Outcome allowed b S) : ¬ Outcome allowed (!b) S := by
  induction h with
  | win S n ha hl hn hlose ih =>
    intro h'
    cases h' with
    | lose _ hall => exact ih (hall n ha hl hn)
  | lose S hall ih =>
    intro h'
    cases h' with
    | win _ n ha hl hn hlose => exact ih n ha hl hn hlose

/-- "Naming `2` is a winning first move" in the game with move set `allowed`: `2` may be named
in the empty position, and then the player to move (the second player) loses. -/
def NamingTwoWins (allowed : ℕ → Prop) : Prop :=
  allowed 2 ∧ Legal ∅ 2 ∧ Outcome allowed false {2}

/-- First claim of the conjecture: naming `2` is a winning first move. -/
def Claim1 : Prop := NamingTwoWins anyNumber

/-- Third claim of the conjecture: in the prime version the winning first moves are exactly
`2`. -/
def Claim3 : Prop :=
  ∀ n : ℕ, (primeOrOne n ∧ Legal ∅ n ∧ Outcome primeOrOne false {n}) ↔ n = 2

/-- `3` is not a multiple of `2`, so it is a legal reply to `2`. -/
theorem legal_three : Legal {2} 3 := by
  refine ⟨by norm_num, ?_⟩
  simp only [Finset.coe_singleton, AddSubmonoid.mem_closure_singleton, smul_eq_mul]
  rintro ⟨k, hk⟩
  omega

/-- Every integer `n ≥ 2` is a sum of `2`s and `3`s, so after `2` and `3` only `1` is legal. -/
theorem legal_after_two_three {n : ℕ} (h : Legal (insert 3 {2}) n) : n = 1 := by
  obtain ⟨hpos, hn⟩ := h
  by_contra h1
  apply hn
  have h2 : (2 : ℕ) ∈ AddSubmonoid.closure ((insert 3 {2} : Finset ℕ) : Set ℕ) :=
    AddSubmonoid.subset_closure (by simp)
  have h3 : (3 : ℕ) ∈ AddSubmonoid.closure ((insert 3 {2} : Finset ℕ) : Set ℕ) :=
    AddSubmonoid.subset_closure (by simp)
  rcases Nat.even_or_odd n with ⟨k, hk⟩ | ⟨k, hk⟩
  · have : n = k • 2 := by rw [smul_eq_mul]; omega
    rw [this]
    exact AddSubmonoid.nsmul_mem _ h2 k
  · have : n = (k - 1) • 2 + 3 := by rw [smul_eq_mul]; omega
    rw [this]
    exact AddSubmonoid.add_mem _ (AddSubmonoid.nsmul_mem _ h2 _) h3

/-- After `2` and `3` the player to move loses, whatever the move set. -/
theorem lose_after_two_three (allowed : ℕ → Prop) : Outcome allowed false (insert 3 {2}) :=
  Outcome.lose _ fun _ _ hl hn => absurd (legal_after_two_three hl) hn

/-- After the first player names `2`, the second player wins by naming `3`, in any version of
the game where `3` may be named. -/
theorem second_player_wins (allowed : ℕ → Prop) (h3 : allowed 3) :
    Outcome allowed true {2} :=
  Outcome.win _ 3 h3 legal_three (by norm_num) (lose_after_two_three allowed)

/-- **The first claim fails**: naming `2` is not a winning first move. -/
theorem not_claim1 : ¬ Claim1 := fun ⟨_, _, hlose⟩ =>
  not_win_and_lose anyNumber (second_player_wins anyNumber trivial) hlose

/-- **The third claim fails**: in the prime version, `2` is not a winning first move either,
because the reply `3` is prime. -/
theorem not_claim3 : ¬ Claim3 := by
  intro h
  obtain ⟨_, _, hlose⟩ := (h 2).2 rfl
  exact not_win_and_lose primeOrOne (second_player_wins primeOrOne (Or.inr Nat.prime_three))
    hlose

/-- **Conjecture 00000008869 is false**: both its first and its third claims fail. Whatever
the second claim (`P`) means, the conjunction of the three claims is false. -/
theorem conjecture_00000008869_false (P : Prop) : ¬ (Claim1 ∧ P ∧ Claim3) :=
  fun h => not_claim1 h.1

end Submission00000008869

#print axioms Submission00000008869.conjecture_00000008869_false
#print axioms Submission00000008869.not_claim3
