#!/usr/bin/env python3
"""
Reproduction script for the refutation of conjecture 00000000807:
"The maximal multiplicity of lambda_1(T^2) is 4 (attained only on the
square torus), and at most 3 for general lattices."

Verdict: FALSE.  For a flat 2-torus R^2 / Lambda the Laplace eigenvalues are
    4 * pi^2 * |k|^2,   k in the dual lattice Lambda*,
so the multiplicity of the first non-zero eigenvalue lambda_1 equals the
number of shortest non-zero vectors of Lambda*.

This script computes, with exact rational arithmetic (stdlib only):
  * the dual basis and dual Gram matrix of the triangular lattice,
  * the number of shortest non-zero dual vectors:  6  (not <= 4),
  * the square lattice case:  4,
  * a generic irrational (rectangular) case:  2,
  * the 60-degree / kissing-number bound proving 6 is the maximum.

Exit status is 0 when every check passes.
"""

import math
import sys
from fractions import Fraction

# --------------------------------------------------------------------------
# 2x2 exact linear algebra over Q
# --------------------------------------------------------------------------

def gram_inv_2x2(g):
    """Inverse of a 2x2 symmetric Gram matrix with rational entries."""
    a, b = g[0]
    c, d = g[1]
    det = a * d - b * c
    if det == 0:
        raise ValueError("singular Gram matrix")
    return [[d / det, -b / det], [-c / det, a / det]]


def inner(g, u, v):
    """Inner product u^T G v for row-vector integer coordinates u, v."""
    return (u[0] * g[0][0] * v[0] + u[0] * g[0][1] * v[1]
            + u[1] * g[1][0] * v[0] + u[1] * g[1][1] * v[1])


def norm2(g, u):
    return inner(g, u, u)


def shortest_dual_vectors(gdual, radius=8):
    """All shortest non-zero integer vectors for the quadratic form gdual.

    Returns (min_norm2, sorted list of coordinate pairs).
    The radius is safe because gdual is positive definite with bounded
    eigenvalues for the lattices considered here.
    """
    best = None
    vecs = []
    for m in range(-radius, radius + 1):
        for n in range(-radius, radius + 1):
            if m == 0 and n == 0:
                continue
            q = norm2(gdual, (m, n))
            if best is None or q < best:
                best = q
                vecs = [(m, n)]
            elif q == best:
                vecs.append((m, n))
    return best, sorted(vecs)


def as_set(vecs):
    return {v for v in vecs}


# --------------------------------------------------------------------------
# Lattices
# --------------------------------------------------------------------------

# Triangular (equilateral) lattice Lambda = Z(1,0) + Z(1/2, sqrt(3)/2).
# Gram matrix with respect to the basis b1=(1,0), b2=(1/2,sqrt(3)/2):
G_TRI = [[Fraction(1), Fraction(1, 2)],
         [Fraction(1, 2), Fraction(1)]]

# Square lattice Z^2.
G_SQUARE = [[Fraction(1), Fraction(0)],
            [Fraction(0), Fraction(1)]]

# Generic irrational rectangular lattice: generated by (1,0) and (0,sqrt(2)).
G_GENERIC = [[Fraction(1), Fraction(0)],
             [Fraction(0), Fraction(2)]]


def dual_basis_triangular():
    """Return the dual basis vectors d1, d2 of the triangular lattice.

    d_i = sum_j (G^{-1})_{j i} b_j, with b1=(1,0), b2=(1/2,sqrt(3)/2).
    Exact answers: d1 = (1, -1/sqrt(3)), d2 = (0, 2/sqrt(3)).
    Returns (d1, d2) as (a, b) meaning a + b*sqrt(3).
    """
    gi = gram_inv_2x2(G_TRI)
    # b1 = (1, 0), b2 = (1/2, sqrt(3)/2)
    d1 = (gi[0][0] * 1 + gi[1][0] * Fraction(1, 2),
          gi[1][0] * Fraction(1, 2))
    d2 = (gi[0][1] * 1 + gi[1][1] * Fraction(1, 2),
          gi[1][1] * Fraction(1, 2))
    return d1, d2


def floating(vec_ab):
    """(a, b) meaning a + b*sqrt(3) -> float coordinates."""
    return (float(vec_ab[0]), float(vec_ab[1]) * math.sqrt(3))


def main():
    checks = []

    def check(name, ok, detail=""):
        checks.append((name, bool(ok), detail))
        print(f"[{'PASS' if ok else 'FAIL'}] {name}" + (f"  ({detail})" if detail else ""))

    print("=" * 72)
    print("conjecture 00000000807 -- multiplicity of lambda_1(T^2)")
    print("=" * 72)

    # ---- Triangular lattice: dual Gram matrix -----------------------------
    gtri_dual = gram_inv_2x2(G_TRI)
    expected_dual = [[Fraction(4, 3), Fraction(-2, 3)],
                     [Fraction(-2, 3), Fraction(4, 3)]]
    check("triangular dual Gram matrix = G^{-1} = [[4/3,-2/3],[-2/3,4/3]]",
          gtri_dual == expected_dual,
          f"got {[[str(x) for x in row] for row in gtri_dual]}")

    d1, d2 = dual_basis_triangular()
    check("dual basis d1 = (1, -1/sqrt(3)), d2 = (0, 2/sqrt(3))",
          d1 == (Fraction(1), Fraction(-1, 3)) and d2 == (Fraction(0), Fraction(2, 3)),
          f"d1 = {d1[0]} + {d1[1]}*sqrt(3), d2 = {d2[0]} + {d2[1]}*sqrt(3)")

    # Verify the dual relations <d_i, b_j> = delta_ij numerically exactly
    # using floats (the exact Gram inverse already certifies this).
    D1, D2 = floating(d1), floating(d2)
    b1, b2 = (1.0, 0.0), (0.5, math.sqrt(3) / 2.0)

    def dot(u, v):
        return u[0] * v[0] + u[1] * v[1]

    dual_ok = (abs(dot(D1, b1) - 1) < 1e-12 and abs(dot(D1, b2)) < 1e-12
               and abs(dot(D2, b1)) < 1e-12 and abs(dot(D2, b2) - 1) < 1e-12)
    check("dual relations <d_i, b_j> = delta_ij", dual_ok)

    # ---- Triangular lattice: shortest dual vectors -------------------------
    tri_min, tri_vecs = shortest_dual_vectors(gtri_dual)
    tri_expected = {(1, 0), (-1, 0), (0, 1), (0, -1), (1, 1), (-1, -1)}
    check("triangular torus: number of shortest non-zero dual vectors is 6",
          len(tri_vecs) == 6 and as_set(tri_vecs) == tri_expected,
          f"count = {len(tri_vecs)}, vectors = {tri_vecs}")
    check("triangular torus: common squared length = 4/3",
          tri_min == Fraction(4, 3), f"min |k|^2 = {tri_min}")
    check("triangular torus: multiplicity 6 > 4 contradicts the conjecture",
          len(tri_vecs) == 6 and 6 > 4)

    # ---- Square lattice ----------------------------------------------------
    sq_min, sq_vecs = shortest_dual_vectors(gram_inv_2x2(G_SQUARE))
    sq_expected = {(1, 0), (-1, 0), (0, 1), (0, -1)}
    check("square torus: number of shortest non-zero dual vectors is 4",
          len(sq_vecs) == 4 and as_set(sq_vecs) == sq_expected,
          f"count = {len(sq_vecs)}, vectors = {sq_vecs}")
    check("square torus: common squared length = 1",
          sq_min == Fraction(1), f"min |k|^2 = {sq_min}")

    # ---- Generic irrational lattice ---------------------------------------
    gen_dual = gram_inv_2x2(G_GENERIC)
    gen_min, gen_vecs = shortest_dual_vectors(gen_dual)
    check("generic (irrational rectangular) torus: multiplicity is 2",
          len(gen_vecs) == 2, f"count = {len(gen_vecs)}, vectors = {gen_vecs}")
    check("generic torus: common squared length = 1/2",
          gen_min == Fraction(1, 2), f"min |k|^2 = {gen_min}")

    check("all multiplicities are even (vectors come in +/- pairs)",
          all(len(v) % 2 == 0 for v in (tri_vecs, sq_vecs, gen_vecs)))

    # ---- 60-degree / kissing-number bound ---------------------------------
    # For any two distinct shortest vectors u, v, the difference u - v is a
    # non-zero lattice vector, so |u-v|^2 >= r^2.  With |u|=|v|=r this gives
    # 2r^2 - 2<u,v> >= r^2, i.e. <u,v> <= r^2/2, i.e. angle(u,v) >= 60 deg.
    # On a circle, k points with pairwise angular separation >= 60 deg occupy
    # k gaps summing to 360 deg, hence 60k <= 360, i.e. k <= 6.
    angles = []
    for (m, n) in tri_vecs:
        x = m * D1[0] + n * D2[0]
        y = m * D1[1] + n * D2[1]
        angles.append(math.degrees(math.atan2(y, x)) % 360.0)
    angles.sort()
    gaps = [angles[(i + 1) % len(angles)] - angles[i] for i in range(len(angles))]
    gaps = [g + 360.0 if g <= 0 else g for g in gaps]
    min_gap = min(gaps)
    check("triangular shortest vectors realize six points separated by 60 deg",
          abs(min_gap - 60.0) < 1e-9 and len(tri_vecs) == 6,
          f"min angular gap = {min_gap:.6f} deg")

    max_points = math.floor(360.0 / 60.0 + 1e-9)
    check("kissing-number bound: pairwise separation >= 60 deg implies <= 6",
          max_points == 6 and 6 * 60 == 360 and 7 * 60 > 360,
          "360/60 = 6; 7 points would need >= 420 deg")

    # ---- Conclusion --------------------------------------------------------
    print("-" * 72)
    print("Conclusion: the maximal multiplicity of lambda_1(T^2) is 6,")
    print("attained by lattices similar to the triangular lattice; it is not 4,")
    print("and the square torus (multiplicity 4) is not the unique maximiser.")
    print("The clause 'at most 3 for general lattices' is also false")
    print("(square: 4, triangular: 6).")
    print("-" * 72)

    failed = [name for name, ok, _ in checks if not ok]
    if failed:
        print(f"\nRESULT: FAIL ({len(failed)} check(s) failed)")
        for name in failed:
            print(f"  - {name}")
        return 1
    print(f"\nRESULT: PASS (all {len(checks)} checks passed)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
