/-
  Axiom audit for the formalisation in `Main.lean`.

  Build/run with:
      lake env lean Check.lean

  Every theorem below should report only core axioms; in particular none may
  report `sorryAx` and none depends on Mathlib.
-/

import Main

open Tlmc2051

-- In any band, the subsemigroup generated by one element is a singleton
#print axioms genByOne_eq
#print axioms genByOne_subsingleton
#print axioms oneGenBand_singleton

-- The free band on one generator is the one-element band (universal property)
#print axioms unitBand_free
#print axioms freeBand_one_singleton

-- The explicit six-element band on Fin 6
#print axioms sixMul_assoc
#print axioms sixMul_idem
#print axioms sixBand_has_six_elements
#print axioms sixBand_generated_by_two
#print axioms band_reduce_sound

-- Catalan numbers and the conjectured closed form
#print axioms cat_one
#print axioms cat_two
#print axioms cat_three
#print axioms formula_at_one
#print axioms formula_at_two
#print axioms formula_at_three

-- The free-band orders and the arithmetic failures
#print axioms freeBand_one_eq_one
#print axioms freeBand_two_eq_six
#print axioms freeBand_three_eq_159
#print axioms failure_at_one
#print axioms failure_at_two
#print axioms failure_at_three

-- The packaged disproof
#print axioms conjecture_00000002051_false_at_one
#print axioms conjecture_00000002051_false_at_two
#print axioms conjecture_00000002051_false_at_three
#print axioms conjecture_00000002051_false
