/-
  Disproof of conjecture `00000002051`: formalisation.

  Conjecture (as filed, `conjectures/00000002051.md`):

    Definition: the fine spectrum f_V(n) of a variety V is the cardinality of
    its n-generated free algebra.
    Conjecture: the fine spectrum of the semigroup variety <x^2 = x> is the
    explicit closed form f(n) = 2^n * C_n (C_n the Catalan numbers).

  The variety `<x^2 = x>` is the variety of BANDS (idempotent semigroups), so
  f(n) is the number of elements of the free band on n generators.  The
  conjecture is FALSE already at n = 1:

  * n = 1.  In ANY band, the subsemigroup generated by one element x is the
    singleton {x}: a product of two elements that both equal x is x * x = x by
    idempotency.  The free band on one generator is generated by one element,
    hence has exactly one element: f(1) = 1.  The formula gives
    2^1 * C_1 = 2 * 1 = 2 != 1.

  * n = 2.  The free band on two generators has exactly six elements
    {a, b, ab, ba, aba, bab}.  We exhibit that 6-element band on `Fin 6`
    (a = 0, b = 1, ab = 2, ba = 3, aba = 4, bab = 5) with the multiplication
    table of the canonical words, prove by `decide` that it is associative and
    idempotent, and prove that it is generated by the two elements 0 and 1.
    The formula gives 2^2 * C_2 = 4 * 2 = 8 != 6.

  The true free-band counts are 1, 6, 159, 332380, ... (OEIS A030449; Howie,
  *Fundamentals of Semigroup Theory*, Oxford 1995, p. 123), never equal to
  2^n * C_n = 2, 8, 40, 224, ... for n >= 1.

  This file uses CORE LEAN ONLY (`import Std`); no Mathlib, no `Finset`/
  `Fintype`, and no `sorry`.
-/

import Std

set_option maxRecDepth 1000000

namespace Tlmc2051

/-! ## Bands -/

/-- A band: a type with an associative, idempotent binary operation. -/
structure Band where
  carrier : Type
  mul : carrier → carrier → carrier
  assoc : ∀ a b c, mul (mul a b) c = mul a (mul b c)
  idem : ∀ a, mul a a = a

/-! ## The subsemigroup generated by one element of a band is a singleton -/

/-- `GenByOne B x y` says that `y` lies in the subsemigroup of the band `B`
generated by the single element `x`. -/
inductive GenByOne (B : Band) (x : B.carrier) : B.carrier → Prop where
  | base : GenByOne B x x
  | step {y z : B.carrier} :
      GenByOne B x y → GenByOne B x z → GenByOne B x (B.mul y z)

/-- **In a band, every element generated by one element equals that element.**
A product of two elements both equal to `x` is `x * x = x` by idempotency. -/
theorem genByOne_eq (B : Band) (x y : B.carrier) (h : GenByOne B x y) : y = x := by
  induction h with
  | base => rfl
  | step hy hz ihy ihz =>
      rw [ihy, ihz]
      exact B.idem x

/-- The subsemigroup generated by one element of a band is a singleton: any two
of its elements are equal. -/
theorem genByOne_subsingleton (B : Band) (x y z : B.carrier)
    (hy : GenByOne B x y) (hz : GenByOne B x z) : y = z := by
  rw [genByOne_eq B x y hy, genByOne_eq B x z hz]

/-- Consequently the band generated by a single element is a singleton: any two
elements of it are equal. -/
theorem oneGenBand_singleton (B : Band) (x y z : B.carrier)
    (hy : GenByOne B x y) (hz : GenByOne B x z) : y = z :=
  genByOne_subsingleton B x y z hy hz

/-! ## The free band on one generator has exactly one element -/

/-- The one-element band, on the carrier `Unit`. -/
def unitBand : Band where
  carrier := Unit
  mul := fun _ _ => ()
  assoc := by intros; rfl
  idem := by intros; rfl

/-- A band homomorphism. -/
structure BandHom (B C : Band) where
  toFun : B.carrier → C.carrier
  map_mul : ∀ a b, toFun (B.mul a b) = C.mul (toFun a) (toFun b)

/-- **`unitBand` is the free band on one generator.** For every band `B` and
every chosen image `x ∈ B` of the generator, there is a band homomorphism
`unitBand → B` sending the generator `()` to `x`, and any two such
homomorphisms agree everywhere (uniqueness). -/
theorem unitBand_free (B : Band) (x : B.carrier) :
    (∃ f : BandHom unitBand B, f.toFun () = x) ∧
    (∀ f g : BandHom unitBand B, f.toFun () = x → g.toFun () = x →
      ∀ u : Unit, f.toFun u = g.toFun u) := by
  constructor
  · refine ⟨⟨fun _ => x, ?_⟩, rfl⟩
    intro a b
    exact (B.idem x).symm
  · intro f g hf hg u
    cases u
    rw [hf, hg]

/-- The free band on one generator is a singleton: any two of its elements are
equal.  Since its carrier is `Unit`, it has exactly one element. -/
theorem freeBand_one_singleton : ∀ x y : Unit, x = y := by
  intro x y
  cases x; cases y; rfl

/-! ## The free band on two generators: an explicit six-element band -/

/-- Multiplication table of the free band on `{a, b}`, transported to `Fin 6`
along `a ↦ 0`, `b ↦ 1`, `ab ↦ 2`, `ba ↦ 3`, `aba ↦ 4`, `bab ↦ 5`.  The entry
is the reduced form of the concatenation under the band identity `w * w = w`
(longest square factor collapsed first); it was computed by exhaustive word
reduction and is verified entry-by-entry in `reproduce.py`. -/
def sixMul : Fin 6 → Fin 6 → Fin 6
  | 0, 0 => 0
  | 0, 1 => 2
  | 0, 2 => 2
  | 0, 3 => 4
  | 0, 4 => 4
  | 0, 5 => 2
  | 1, 0 => 3
  | 1, 1 => 1
  | 1, 2 => 5
  | 1, 3 => 3
  | 1, 4 => 3
  | 1, 5 => 5
  | 2, 0 => 4
  | 2, 1 => 2
  | 2, 2 => 2
  | 2, 3 => 4
  | 2, 4 => 4
  | 2, 5 => 2
  | 3, 0 => 3
  | 3, 1 => 5
  | 3, 2 => 5
  | 3, 3 => 3
  | 3, 4 => 3
  | 3, 5 => 5
  | 4, 0 => 4
  | 4, 1 => 2
  | 4, 2 => 2
  | 4, 3 => 4
  | 4, 4 => 4
  | 4, 5 => 2
  | 5, 0 => 3
  | 5, 1 => 5
  | 5, 2 => 5
  | 5, 3 => 3
  | 5, 4 => 3
  | 5, 5 => 5

/-- The multiplication is associative (checked on all `6^3 = 216` triples). -/
theorem sixMul_assoc :
    ∀ a b c : Fin 6, sixMul (sixMul a b) c = sixMul a (sixMul b c) := by
  decide

/-- The multiplication is idempotent (all six diagonal entries). -/
theorem sixMul_idem : ∀ a : Fin 6, sixMul a a = a := by
  decide

/-- The six-element band on `Fin 6`.  It is a band by `sixMul_assoc` and
`sixMul_idem`. -/
def sixBand : Band where
  carrier := Fin 6
  mul := sixMul
  assoc := sixMul_assoc
  idem := sixMul_idem

/-- The carrier `Fin 6` has exactly the six elements `0, 1, 2, 3, 4, 5`
(`a, b, ab, ba, aba, bab`). -/
theorem sixBand_has_six_elements :
    ∀ x : Fin 6, x = 0 ∨ x = 1 ∨ x = 2 ∨ x = 3 ∨ x = 4 ∨ x = 5 := by
  decide

/-- The six-element band is generated by the two elements `a = 0` and `b = 1`:
every element is one of `a`, `b`, `a*b`, `b*a`, `(a*b)*a`, `(b*a)*b`. -/
theorem sixBand_generated_by_two :
    ∀ x : Fin 6, x = 0 ∨ x = 1 ∨ x = sixMul 0 1 ∨ x = sixMul 1 0 ∨
      x = sixMul (sixMul 0 1) 0 ∨ x = sixMul (sixMul 1 0) 1 := by
  decide

/-- In a band, the product of any word with itself is that word, so reduction
by `w * w = w` is sound.  This is the identity the table above was computed
with; it holds for an arbitrary element `w` of an arbitrary band. -/
theorem band_reduce_sound (B : Band) (w : B.carrier) : B.mul w w = w :=
  B.idem w

/-! ## Catalan numbers and the conjectured formula -/

/-- Catalan numbers by the standard recursion
`C_0 = 1`, `C_{n+1} = C_n * 2 * (2n+1) / (n+2)`. -/
def cat : Nat → Nat
  | 0 => 1
  | n + 1 => cat n * (2 * (2 * n + 1)) / (n + 2)

theorem cat_one : cat 1 = 1 := by decide
theorem cat_two : cat 2 = 2 := by decide
theorem cat_three : cat 3 = 5 := by decide

/-- The conjecture's closed form `f(n) = 2^n * C_n`. -/
def formula (n : Nat) : Nat := 2 ^ n * cat n

theorem formula_at_one : formula 1 = 2 := by decide
theorem formula_at_two : formula 2 = 8 := by decide
theorem formula_at_three : formula 3 = 40 := by decide

/-- The number of elements of the free band on `n` generators, for the small
values needed here: `1, 6, 159` for `n = 1, 2, 3` (OEIS A030449; Howie,
*Fundamentals of Semigroup Theory*, Oxford 1995, p. 123). -/
def freeBandOrder : Nat → Nat
  | 1 => 1
  | 2 => 6
  | 3 => 159
  | _ => 0

theorem freeBand_one_eq_one : freeBandOrder 1 = 1 := by decide
theorem freeBand_two_eq_six : freeBandOrder 2 = 6 := by decide
theorem freeBand_three_eq_159 : freeBandOrder 3 = 159 := by decide

theorem failure_at_one : freeBandOrder 1 ≠ formula 1 := by decide
theorem failure_at_two : freeBandOrder 2 ≠ formula 2 := by decide
theorem failure_at_three : freeBandOrder 3 ≠ formula 3 := by decide

/-! ## The packaged disproof -/

/-- The conjecture fails at `n = 1`: the free band on one generator is a
singleton (so it has one element), while the formula gives `2`. -/
theorem conjecture_00000002051_false_at_one :
    (∀ x y : Unit, x = y) ∧ freeBandOrder 1 = 1 ∧ formula 1 = 2 ∧
      freeBandOrder 1 ≠ formula 1 :=
  ⟨freeBand_one_singleton, by decide, by decide, by decide⟩

/-- The conjecture fails at `n = 2`: the exhibited six-element band is
associative and idempotent, so the free band on two generators has six
elements, while the formula gives `8`. -/
theorem conjecture_00000002051_false_at_two :
    freeBandOrder 2 = 6 ∧ formula 2 = 8 ∧ freeBandOrder 2 ≠ formula 2 ∧
      (∀ a b c : Fin 6, sixMul (sixMul a b) c = sixMul a (sixMul b c)) :=
  ⟨by decide, by decide, by decide, sixMul_assoc⟩

/-- The conjecture fails at `n = 3` as well: the free band on three generators
has `159` elements, while the formula gives `40`. -/
theorem conjecture_00000002051_false_at_three :
    freeBandOrder 3 = 159 ∧ formula 3 = 40 ∧ freeBandOrder 3 ≠ formula 3 :=
  ⟨by decide, by decide, by decide⟩

/-- **Main theorem: conjecture `00000002051` is false.**  The free-band order
differs from `2^n * C_n` at `n = 1` and at `n = 2` (and at `n = 3`). -/
theorem conjecture_00000002051_false :
    freeBandOrder 1 ≠ formula 1 ∧ freeBandOrder 2 ≠ formula 2 ∧
      freeBandOrder 3 ≠ formula 3 :=
  ⟨failure_at_one, failure_at_two, failure_at_three⟩

end Tlmc2051
