name = "conjecture3968"
version = "0.1.0"
defaultTargets = ["Conjecture3968"]

[leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.33.1"

[[lean_lib]]
name = "Conjecture3968"
