import TLMC69.Main

#print axioms TLMC69.approximant_eval
#print axioms TLMC69.approximant_degree
#print axioms TLMC69.approximant_even
#print axioms TLMC69.primitive_kernel_bounds
#print axioms TLMC69.approximant_le
#print axioms TLMC69.even_integral
#print axioms TLMC69.approximant_error_exact
#print axioms TLMC69.Q_even
#print axioms TLMC69.Q_zero
#print axioms TLMC69.quad_degree
#print axioms TLMC69.Q_degree
#print axioms TLMC69.Q_sin
#print axioms TLMC69.abs_sin_nat_mul_le
#print axioms TLMC69.Q_mul_bound
#print axioms TLMC69.Q_bound
#print axioms TLMC69.arcsin_le_twice
#print axioms TLMC69.Q_lower
#print axioms TLMC69.kernel_eval
#print axioms TLMC69.kernel_nonneg
#print axioms TLMC69.kernel_even
#print axioms TLMC69.kernel_degree
#print axioms TLMC69.kernel_bound
#print axioms TLMC69.kernel_weight_bound
#print axioms TLMC69.mass_lower
#print axioms TLMC69.mass_pos
#print axioms TLMC69.moment_nonneg
#print axioms TLMC69.moment_upper
#print axioms TLMC69.l1Error_nonneg
#print axioms TLMC69.errors_nonempty
#print axioms TLMC69.errors_bddBelow
#print axioms TLMC69.bestError_nonneg
#print axioms TLMC69.bestError_le
#print axioms TLMC69.approximant_error_bound
#print axioms TLMC69.bestError_subsequence_bound
#print axioms TLMC69.scaled_bound
#print axioms TLMC69.scaled_subsequence_tendsto_zero
#print axioms TLMC69.no_nonzero_scaled_limit
#print axioms TLMC69.conjecture69_disproof
#print axioms TLMC69.derivative_primitive
#print axioms TLMC69.primitive_zero
#print axioms TLMC69.primitive_deriv
#print axioms TLMC69.primitive_integral
#print axioms TLMC69.primitive_degree
#print axioms TLMC69.primitive_odd
