import Solution

/-! Independent author-stage axiom audit of every explicitly declared object and result. -/

#print axioms TLMC1478.Vector
#print axioms TLMC1478.Tensor
#print axioms TLMC1478.FactorTriple
#print axioms TLMC1478.rankOne
#print axioms TLMC1478.termTensor
#print axioms TLMC1478.termCost
#print axioms TLMC1478.decompositionCosts
#print axioms TLMC1478.nuclearNorm
#print axioms TLMC1478.nuclearBall
#print axioms TLMC1478.termCost_nonneg
#print axioms TLMC1478.decompositionCosts_bddBelow
#print axioms TLMC1478.coordinateTerm
#print axioms TLMC1478.coordinate_expansion
#print axioms TLMC1478.decompositionCosts_nonempty
#print axioms TLMC1478.norm_termTensor_le
#print axioms TLMC1478.norm_list_sum_coordinate_le
#print axioms TLMC1478.coordinate_le_nuclearNorm
#print axioms TLMC1478.nuclearNorm_nonneg
#print axioms TLMC1478.nuclearNorm_eq_minimum
#print axioms TLMC1478.nuclearNorm_rankOne_le
#print axioms TLMC1478.nuclearNorm_zero
#print axioms TLMC1478.basisTensor
#print axioms TLMC1478.basisTensor_origin
#print axioms TLMC1478.nuclearNorm_basisTensor
#print axioms TLMC1478.zero_mem_nuclearBall
#print axioms TLMC1478.basisTensor_mem_nuclearBall
#print axioms TLMC1478.nuclearBall_coordinate_bound
#print axioms TLMC1478.termTensor_eq_zero_iff
#print axioms TLMC1478.termCost_eq_zero_of_tensor_zero
#print axioms TLMC1478.remove_zero_terms
#print axioms TLMC1478.mem_decompositionCosts_iff_nonzero_terms
#print axioms TLMC1478.minimumNuclearBall
#print axioms TLMC1478.minimumNuclearBall_subset
#print axioms TLMC1478.isLeast_cost_of_mem_of_norm_eq
#print axioms TLMC1478.zero_mem_minimumNuclearBall
#print axioms TLMC1478.basisTensor_mem_minimumNuclearBall
#print axioms PolynomialCone.polynomial_eval_eq_eval_zero_of_bounded_nonneg
#print axioms PolynomialCone.rayPolynomial
#print axioms PolynomialCone.eval_rayPolynomial
#print axioms PolynomialCone.eval_eq_eval_zero_of_bounded_on_cone
#print axioms PolynomialCone.polynomial_map_eq_zero_of_bounded_on_cone
#print axioms PolynomialCone.exists_real_imag_polynomials
#print axioms TLMC1478.TensorPolynomialMap
#print axioms TLMC1478.TensorPolynomialMap.eval
#print axioms TLMC1478.complex_polynomials_represented
#print axioms TLMC1478.IsCone
#print axioms TLMC1478.no_polynomial_cone_image_between
#print axioms TLMC1478.nuclearBall_not_polynomial_image_of_cone
#print axioms TLMC1478.minimumNuclearBall_not_polynomial_image_of_cone
#print axioms TLMC1478.spectrahedralCone4
#print axioms TLMC1478.posSemidef_smul_nonneg
#print axioms TLMC1478.spectrahedralCone4_isCone
#print axioms TLMC1478.nuclearBall_not_polynomial_image_of_spectrahedralCone4
#print axioms TLMC1478.conjecture00000001478_false
