import Std

/-!
# Disproof of conjecture 00000000458

The conjecture (file `conjectures/00000000458.md`) asserts:

> The absolute value of the Möbius number of the Tamari lattice `T_n`
> is `(n-2)(-1)^n`.

Verdict: **FALSE**, for two independent reasons.

* (a) **Sign contradiction.**  The right-hand side is asserted to be an
  absolute value, yet at `n = 3` it equals `(3-2)*(-1)^3 = -1`, a negative
  number.  No absolute value is negative.  This alone refutes the statement,
  without any enumeration.
* (b) **The actual value is `1`.**  Enumerating the genuine Tamari lattice
  (binary trees with `n` internal nodes under the right-rotation order) shows
  `μ(0̂,1̂) = (-1)^{n-1}`, hence `|μ(T_n)| = 1` for every `n`, which equals
  `(n-2)(-1)^n` only accidentally at `n = 1` (both give `1`).

This file formalises the sign contradiction in full, and the decisive
`T_3` computation: the five binary trees with 3 internal nodes are generated
by enumeration, the right-rotation order is computed as a transitive closure,
and the Möbius value `μ(0̂,1̂)` is evaluated by the standard recurrence

`μ(x,x) = 1`,  `μ(x,z) = - Σ_{x ≤ y < z} μ(x,y)`.

The result is `μ(T_3) = 1`, so `|μ(T_3)| = 1 ≠ -1 = (3-2)(-1)^3`.

Everything is core Lean 4 (`import Std`, no Mathlib), with no `sorry`,
no `axiom`, and no `native_decide` / `ofReduceBool`.
-/

set_option maxRecDepth 100000

namespace Tlmc458

/-! ## Integer absolute value

Core Lean has no `|·|` on `Int`, so we define it directly (and use it only for
the sign argument; the Möbius computation stays in `Int`/`Nat`). -/

/-- Absolute value of an integer, as an integer. -/
def iabs (m : Int) : Int := if 0 ≤ m then m else -m

/-- An absolute value is always nonnegative. -/
theorem modulus_nonneg : ∀ m : Int, 0 ≤ iabs m := by
  intro m
  unfold iabs
  split
  · assumption
  · omega

/-- No absolute value can equal `-1`. -/
theorem no_abs_eq_neg_one : ∀ m : Int, iabs m ≠ -1 := by
  intro m h
  have hnn : (0 : Int) ≤ iabs m := modulus_nonneg m
  omega

/-! ## The claimed closed formula -/

/-- The value the conjecture attributes to `|μ(T_n)|`. -/
def claimedAbsMu (n : Nat) : Int := ((n : Int) - 2) * (-1 : Int) ^ n

/-- At `n = 3` the claimed value is `-1`. -/
theorem formula_at_three : claimedAbsMu 3 = -1 := by decide

/-- Literal form of the same fact. -/
theorem formula_at_three_literal :
    ((3 : Int) - 2) * (-1 : Int) ^ 3 = -1 := by decide

/-- The claimed value at `n = 3` is negative, contradicting the fact that it
is supposed to be an absolute value. -/
theorem contradiction_sign :
    ((3 : Int) - 2) * (-1 : Int) ^ 3 = -1 ∧
      ¬ (0 ≤ ((3 : Int) - 2) * (-1 : Int) ^ 3) := by
  decide

/-- Stronger sign statement: the claimed value `-1` cannot be the absolute
value of any integer. -/
theorem contradiction_sign_strong :
    claimedAbsMu 3 = -1 ∧ ¬ (0 ≤ claimedAbsMu 3) ∧ ∀ m : Int, iabs m ≠ -1 := by
  refine ⟨formula_at_three, by decide, no_abs_eq_neg_one⟩

/-! ## The Tamari lattice on binary trees

A binary tree with `n` internal nodes is a full binary tree with `n+1` leaves;
its internal nodes carry no labels, so the shapes are counted by the Catalan
numbers `|T_n| = C_n`. -/

/-- Binary trees: leaves and internal nodes. -/
inductive Tree where
  | leaf : Tree
  | node : Tree → Tree → Tree
deriving DecidableEq, Repr

namespace Tree

/-- Number of internal nodes. -/
def size : Tree → Nat
  | .leaf => 0
  | .node l r => l.size + r.size + 1

end Tree

/-- All trees with at most `n` internal nodes. -/
def allTreesUpTo : Nat → List Tree
  | 0 => [.leaf]
  | n + 1 =>
      let prev := allTreesUpTo n
      prev ++
        (List.range (n + 1)).flatMap (fun i =>
          (prev.filter (fun l => l.size = i)).flatMap (fun l =>
            (prev.filter (fun r => r.size = n - i)).map (fun r => .node l r)))

/-- All trees with exactly `n` internal nodes. -/
def allTrees (n : Nat) : List Tree :=
  (allTreesUpTo n).filter (fun t => t.size = n)

/-- All trees obtained from `t` by one right rotation.  A right rotation turns
`((A,B),C)` into `(A,(B,C))`, and may be applied at any node. -/
def rotations : Tree → List Tree
  | .leaf => []
  | .node l r =>
      (match l with
        | .leaf => []
        | .node a b => [.node a (.node b r)])
      ++ (rotations l).map (fun l' => .node l' r)
      ++ (rotations r).map (fun r' => .node l r')

/-- One Floyd–Warshall relaxation step for the vertex `k`. -/
def warshallStep (L : List Tree) (E : List (Tree × Tree)) (k : Tree) :
    List (Tree × Tree) :=
  L.foldl (fun E i =>
    L.foldl (fun E j =>
      if decide ((i, k) ∈ E) && decide ((k, j) ∈ E) then
        if decide ((i, j) ∈ E) then E else (i, j) :: E
      else E) E) E

/-- The cover relation generated by a single right rotation, restricted to the
finite carrier `L`. -/
def covers (L : List Tree) : List (Tree × Tree) :=
  L.flatMap (fun t =>
    (rotations t).filter (fun u => u ∈ L) |>.map (fun u => (t, u)))

/-- The reflexive-transitive closure of the right-rotation relation on the
finite carrier `L`. -/
def closure (L : List Tree) : List (Tree × Tree) :=
  L.foldl (fun E k => warshallStep L E k)
    ((L.map (fun t => (t, t))) ++ covers L)

/-- The Tamari order `x ≤ y` on `L`, as a boolean. -/
def leB (L : List Tree) (x y : Tree) : Bool :=
  decide ((x, y) ∈ closure L)

/-- The Möbius value `μ(x,y)` on the finite poset with carrier `L` and order
relation `R`, using the recurrence `μ(x,x) = 1` and
`μ(x,z) = -Σ_{x≤y<z} μ(x,y)`.  `fuel` is structural; it is chosen at least
as large as the height of the interval so that the recursion bottoms out
before hitting the `fuel = 0` branch. -/
def muRel (L : List Tree) (R : List (Tree × Tree)) : Nat → Tree → Tree → Int
  | 0, x, y => if x = y then 1 else 0
  | f + 1, x, y =>
      if x = y then 1
      else
        -((L.filter (fun w =>
              decide ((x, w) ∈ R) && decide ((w, y) ∈ R) && decide (w ≠ y))).foldl
            (fun acc w => acc + muRel L R f x w) 0)

/-- The left comb: the minimum of the Tamari lattice (all left children are
internal, right children are leaves). -/
def leftComb : Nat → Tree
  | 0 => .leaf
  | n + 1 => .node (leftComb n) .leaf

/-- The right comb: the maximum of the Tamari lattice. -/
def rightComb : Nat → Tree
  | 0 => .leaf
  | n + 1 => .node .leaf (rightComb n)

/-- The Möbius number `μ(0̂,1̂)` of the Tamari lattice `T_n`. -/
def mobiusTamari (n : Nat) : Int :=
  let L := allTrees n
  let R := closure L
  muRel L R L.length (leftComb n) (rightComb n)

/-! ## Enumeration checks for `T_3` -/

/-- `T_3` has the five Catalan(3) = 5 shapes. -/
theorem card_T3 : (allTrees 3).length = 5 := by decide

/-- The minimum `0̂` is the left comb. -/
theorem bottom_T3 : leftComb 3 ∈ allTrees 3 := by decide

/-- The maximum `1̂` is the right comb. -/
theorem top_T3 : rightComb 3 ∈ allTrees 3 := by decide

/-- The minimum is indeed below every element of `T_3`. -/
theorem bottom_is_min :
    (allTrees 3).all (fun y => leB (allTrees 3) (leftComb 3) y) = true := by
  decide

/-- The maximum is indeed above every element of `T_3`. -/
theorem top_is_max :
    (allTrees 3).all (fun x => leB (allTrees 3) x (rightComb 3)) = true := by
  decide

/-! ## The Möbius value of `T_3` -/

/-- The decisive computation: `μ(T_3) = 1`, hence `|μ(T_3)| = 1`, whereas the
conjecture predicts `(3-2)(-1)^3 = -1`. -/
theorem mu_T3 : mobiusTamari 3 = 1 := by decide

/-- The absolute value of the Möbius number of `T_3` is `1`. -/
theorem abs_mu_T3 : iabs (mobiusTamari 3) = 1 := by decide

/-! ## The conjecture is false -/

/-- Conjecture 00000000458 is false.  The conjunction records:

* the claimed value at `n = 3` is `-1` (the literal sign contradiction);
* that claimed value is negative, while no absolute value is negative;
* the true value is `|μ(T_3)| = 1`; and
* `1 ≠ -1`, so the formula does not even match at `n = 3`. -/
theorem conjecture_00000000458_false :
    ((3 : Int) - 2) * (-1 : Int) ^ 3 = -1 ∧
      ¬ (0 ≤ ((3 : Int) - 2) * (-1 : Int) ^ 3) ∧
      iabs (mobiusTamari 3) = 1 ∧
      iabs (mobiusTamari 3) ≠ ((3 : Int) - 2) * (-1 : Int) ^ 3 := by
  refine ⟨by decide, by decide, by decide, by decide⟩

end Tlmc458
