/-!
# Refutation of TLMC conjecture 00000003843 (0-Hecke two-sided classes)

Conjecture (verbatim): "The 0-Hecke monoid H_n(0) is generated by monoid braid
relations and absorption relations. The number of two-sided classes of H_n(0) is
exactly the partition number p(n), and the number of left classes in each
two-sided class equals the number of distinct hook lengths of the corresponding
partition."

What is formalised here
-----------------------
Everything is a finite computation.  No analysis, no probability, no external
mathematical library: only the Lean 4 kernel and core.  Every branch is a
`match`, never an `if` -- in particular the short-circuiting operators `&&` and
`||` are avoided, because in Lean 4 they elaborate to `if <Bool> then ... else`,
which goes through `CoeSort Bool Prop` and `Decidable (b = true)` and hence
pulls in `propext`.  With `band`/`bor` defined by pattern matching instead, no
theorem below depends on any axiom (verified with `#print axioms`).

  1. H_3(0) is realised concretely as the six 0-Hecke elements pi_w, w in S_3,
     with the right-descent multiplication rule

         pi_w * pi_i = pi_{w s_i}   if  len(w s_i) > len(w)
                     = pi_w         otherwise.

     Three self-checks are computed: there are 6 elements, the multiplication is
     associative on all 6^3 triples, 0 is a two-sided identity, and both
     generators are idempotent (the absorption relation pi_i^2 = pi_i).

  2. Green's relations are computed by closing a singleton under left and right
     multiplication by the two generators:
         J(a) = H a H   (two-sided principal ideal)
         L(a) = H a     (left principal ideal)
     Then  a J b  iff  J(a) = J(b)  and  a L b  iff  L(a) = L(b), so the number
     of J-classes (resp. L-classes) is the number of distinct principal ideals.
     Both are computed to be 6: H_3(0) is J-trivial, hence also L- and R-trivial.

  3. p(3) = 3 is computed from a definition of integer partitions, and
     sum over partitions lambda of 3 of #distinct hook lengths = 8.

  4. Since 6 != 3 the first half of the conjecture fails at n = 3; since 6 != 8
     the second half fails at n = 3 as well.

Caveat, stated here and in the accompanying write-up: "two-sided classes" is read
as Green's J-classes and "left classes" as Green's L-classes, which is the
standard reading for a monoid.  Section 3 of the write-up gives a second,
independent refutation of the *second* half of the conjecture which is valid
under the alternative Kazhdan-Lusztig reading as well.
-/

namespace Tlmc3843

-- =========================== generic list utilities ===========================

-- Boolean connectives by pattern matching (NOT the && / || macros)
def band : Bool → Bool → Bool
  | true,  b => b
  | false, _ => false

def bor : Bool → Bool → Bool
  | true,  _ => true
  | false, b => b

-- strict order on Nat as a Bool, by structural recursion
def ltB : Nat → Nat → Bool
  | 0,     0     => false
  | 0,     _ + 1 => true
  | _ + 1, 0     => false
  | a + 1, b + 1 => ltB a b

-- min a b written without `if`:  min a b = a - (a - b)
def minB (a b : Nat) : Nat := a - (a - b)

-- Indexing with a default, hand-rolled: the Std function for this pulls in
-- `propext`, while every other core-Lean function used here is axiom-free.
def idxD {α : Type} : List α → Nat → α → α
  | [],      _   => fun d => d
  | a :: _,  0   => fun _ => a
  | _ :: t,  n+1 => fun d => idxD t n d

def memBEq [BEq α] (x : α) : List α → Bool
  | []      => false
  | y :: ys => bor (x == y) (memBEq x ys)

def ins [BEq α] (x : α) (l : List α) : List α :=
  match memBEq x l with
  | true  => l
  | false => x :: l

def nub [BEq α] : List α → List α
  | []      => []
  | y :: ys =>
    match memBEq y ys with
    | true  => nub ys
    | false => y :: nub ys

def posOf [BEq α] (x : α) : List α → Nat
  | []      => 0
  | y :: ys =>
    match x == y with
    | true  => 0
    | false => posOf x ys + 1

def sumList : List Nat → Nat
  | []      => 0
  | y :: ys => y + sumList ys

-- =========================== S_3 and H_3(0) ===========================

-- The six permutations of {0,1,2}, in one-line notation.
def perms3 : List (List Nat) :=
  [[0, 1, 2], [0, 2, 1], [1, 0, 2], [1, 2, 0], [2, 0, 1], [2, 1, 0]]

-- A reduced word for each of them, as a list of generator indices (0 or 1),
-- where generator i swaps the entries in positions i and i+1.
def words3 : List (List Nat) :=
  [[], [1], [0], [0, 1], [1, 0], [0, 1, 0]]

def allIdx : List Nat := [0, 1, 2, 3, 4, 5]

def permOf (k : Nat) : List Nat := idxD perms3 k []
def wordOf (k : Nat) : List Nat := idxD words3 k []

-- swap entries in positions i and i+1
def swapAt : List Nat → Nat → List Nat
  | [],            _   => []
  | a :: [],       _   => [a]
  | a :: b :: t,   0   => b :: a :: t
  | a :: b :: t,   n+1 => a :: swapAt (b :: t) n

-- Coxeter length = number of inversions of the one-line notation
def invCount : List Nat → Nat
  | []      => 0
  | a :: t  => t.foldl (fun acc b =>
                 match ltB b a with
                 | true  => acc + 1
                 | false => acc) 0 + invCount t

-- right multiplication by the generator i:  pi_w * pi_i
def stepP (w : List Nat) (i : Nat) : List Nat :=
  let v := swapAt w i
  match ltB (invCount w) (invCount v) with
  | true  => v
  | false => w

-- the 0-Hecke product, on indices into perms3
def mul (a b : Nat) : Nat :=
  posOf ((wordOf b).foldl stepP (permOf a)) perms3

-- the two generators: index 2 = s_0 = [1,0,2];  index 1 = s_1 = [0,2,1]
def g0 : Nat := 2
def g1 : Nat := 1
def e  : Nat := 0   -- identity, [0,1,2]

def hSize : Nat := (nub (allIdx.map (fun i => permOf i))).length

-- =========================== Green's relations ===========================

-- close a set under the four maps  x |-> x*g0, x*g1, g0*x, g1*x
def growJ (l : List Nat) : List Nat :=
  l.foldl (fun acc x =>
    ins (mul x g0) (ins (mul x g1) (ins (mul g0 x) (ins (mul g1 x) acc)))) l

-- close a set under left multiplication only:  x |-> g0*x, g1*x
def growL (l : List Nat) : List Nat :=
  l.foldl (fun acc x => ins (mul g0 x) (ins (mul g1 x) acc)) l

def closureN (f : List Nat → List Nat) : Nat → List Nat → List Nat
  | 0,   l => l
  | n+1, l => closureN f n (f l)

-- a principal ideal as a canonical characteristic vector over all six elements
def charOf (l : List Nat) : List Bool := allIdx.map (fun i => memBEq i l)

def jIdeal (a : Nat) : List Nat := closureN growJ 6 [a]
def lIdeal (a : Nat) : List Nat := closureN growL 6 [a]

def jVec (a : Nat) : List Bool := charOf (jIdeal a)
def lVec (a : Nat) : List Bool := charOf (lIdeal a)

-- the number of J-classes, resp. L-classes, of H_3(0)
def jClasses : Nat := (nub (allIdx.map jVec)).length
def lClasses : Nat := (nub (allIdx.map lVec)).length

-- =========================== self-checks on the multiplication =================

def assocHolds : Bool :=
  allIdx.foldl (fun acc a =>
    allIdx.foldl (fun acc2 b =>
      allIdx.foldl (fun acc3 c =>
        band (mul (mul a b) c == mul a (mul b c)) acc3) acc2) acc) true

def identityHolds : Bool :=
  allIdx.foldl (fun acc a =>
    band (mul e a == a) (band (mul a e == a) acc)) true

def absorptionHolds : Bool :=
  band (mul g0 g0 == g0) (mul g1 g1 == g1)

-- =========================== partitions and hook lengths =====================

-- partitions of n into non-increasing parts, each at most mx
def partsAux : Nat → Nat → Nat → List (List Nat)
  | 0,      _,   _  => [[]]
  | _,      0,   _  => [[]]
  | fuel+1, n+1, mx =>
      (List.range (minB (n + 1) mx)).flatMap fun j =>
        let k := j + 1
        (partsAux fuel (n + 1 - k) k).map fun rest => k :: rest

def partitionsOf (n : Nat) : List (List Nat) := partsAux (n + 1) n n

def pCount (n : Nat) : Nat := (partitionsOf n).length

-- all hook lengths of a partition (rows given by their lengths)
def hooksOf (l : List Nat) : List Nat :=
  (List.range l.length).flatMap fun i =>
    let li := idxD l i 0
    (List.range li).map fun j =>
      let right := li - j - 1
      let below :=
        ((List.range (l.length - i - 1)).map (fun k => idxD l (i + 1 + k) 0)).foldl
          (fun acc v =>
            match ltB j v with
            | true  => acc + 1
            | false => acc) 0
      right + below + 1

def distinctHooks (l : List Nat) : Nat := (nub (hooksOf l)).length

def sumDistinctHooks (n : Nat) : Nat := sumList ((partitionsOf n).map distinctHooks)

-- =========================== the computation =================================

set_option maxRecDepth 20000

theorem hSize_eq : hSize = 6 := rfl
theorem assoc_ok : assocHolds = true := rfl
theorem identity_ok : identityHolds = true := rfl
theorem absorption_ok : absorptionHolds = true := rfl

theorem jClasses_eq : jClasses = 6 := rfl
theorem lClasses_eq : lClasses = 6 := rfl
theorem pCount3_eq : pCount 3 = 3 := rfl
theorem sumHooks3_eq : sumDistinctHooks 3 = 8 := rfl

-- Boolean witnesses for the two refutations (the actual mathematical content)
theorem refutation_one_bool : (jClasses == pCount 3) = false := rfl
theorem refutation_two_bool : (lClasses == sumDistinctHooks 3) = false := rfl

-- =========================== refutation ======================================

/-- First half of the conjecture fails at n = 3: H_3(0) has 6 two-sided
    (Green J-) classes, but p(3) = 3. -/
theorem refutation_part_one : jClasses ≠ pCount 3 := by
  intro h
  have A : jClasses = 6 := rfl
  have B : pCount 3 = 3 := rfl
  have h' : (6 : Nat) = 3 := Eq.trans (Eq.symm A) (Eq.trans h B)
  nomatch h'

/-- Second half of the conjecture fails at n = 3: H_3(0) has 6 left
    (Green L-) classes in total, while the conjecture predicts
    sum over partitions of 3 of #distinct hook lengths = 8. -/
theorem refutation_part_two : lClasses ≠ sumDistinctHooks 3 := by
  intro h
  have A : lClasses = 6 := rfl
  have B : sumDistinctHooks 3 = 8 := rfl
  have h' : (6 : Nat) = 8 := Eq.trans (Eq.symm A) (Eq.trans h B)
  nomatch h'

theorem summary :
    hSize = 6 ∧ assocHolds = true ∧ identityHolds = true ∧ absorptionHolds = true ∧
    jClasses = 6 ∧ lClasses = 6 ∧ pCount 3 = 3 ∧ sumDistinctHooks 3 = 8 ∧
    jClasses ≠ pCount 3 ∧ lClasses ≠ sumDistinctHooks 3 := by
  exact ⟨rfl, rfl, rfl, rfl, rfl, rfl, rfl, rfl, refutation_part_one, refutation_part_two⟩

end Tlmc3843
