#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Stand-alone reproduction of the refutation of TLMC conjecture 00000003843.

No third-party packages: standard library only.

The 0-Hecke monoid H_n(0) is the monoid generated by pi_1, ..., pi_{n-1} subject
to the braid relations, far-commutation, and the absorption relations
pi_i^2 = pi_i.  Its elements are indexed by permutations w of S_n, so
|H_n(0)| = n!, and the right-descent multiplication rule is

    pi_w * pi_i = pi_{w s_i}   if  len(w s_i) > len(w)
                = pi_w         otherwise,

where w s_i is w with the entries in positions i and i+1 swapped.

This script
  (1) builds H_n(0) for n = 2..5 and self-checks it
      (associativity, two-sided identity, number of idempotents = 2^{n-1});
  (2) computes Green's J-, L- and R-classes by closing singletons under
      multiplication by the generators;
  (3) compares the number of two-sided classes with the partition number p(n)
      and the number of left classes with the sum, over partitions of n, of the
      number of distinct hook lengths;
  (4) prints the six principal two-sided ideals of H_3(0) explicitly.

Expected output (the numbers formalised in lean4/Main.lean):

    n=3:  |H| = 6, J-classes = 6, L-classes = 6, R-classes = 6
          p(3) = 3,  sum over partitions of 3 of #distinct hook lengths = 8
"""

from itertools import permutations


# ----------------------------------------------------------------- H_n(0) ----

def build(n):
    """Return (elements, mul, generators) for the 0-Hecke monoid H_n(0)."""
    G = n - 1
    elems = list(permutations(range(n)))
    index = {w: k for k, w in enumerate(elems)}

    def length(w):                       # Coxeter length = inversion count
        return sum(1 for i in range(n) for j in range(i + 1, n) if w[i] > w[j])

    def swap_positions(w, i):            # w * s_i : swap entries i, i+1
        v = list(w)
        v[i], v[i + 1] = v[i + 1], v[i]
        return tuple(v)

    def swap_values(w, i):               # s_i * w : swap the values i, i+1
        v = list(w)
        a, b = v.index(i), v.index(i + 1)
        v[a], v[b] = v[b], v[a]
        return tuple(v)

    def reduced_word(w):                 # a reduced word for w
        v, out = list(w), []
        for _ in range(n):
            for j in range(n - 1):
                if v[j] > v[j + 1]:
                    v[j], v[j + 1] = v[j + 1], v[j]
                    out.append(j)
        return out[::-1]

    def ract(w, i):                      # pi_w * pi_i
        v = swap_positions(w, i)
        return v if length(v) > length(w) else w

    def lact(w, i):                      # pi_i * pi_w
        v = swap_values(w, i)
        return v if length(v) > length(w) else w

    right = [[index[ract(w, i)] for i in range(G)] for w in elems]
    left = [[index[lact(w, i)] for i in range(G)] for w in elems]
    words = [reduced_word(w) for w in elems]

    def mul(a, b):
        k = a
        for i in words[b]:
            k = right[k][i]
        return k

    return elems, mul, left, right, G


# --------------------------------------------------- Green's relations -------

def closure(seed, maps, size):
    S, frontier = {seed}, {seed}
    while frontier:
        new = set()
        for x in frontier:
            for f in maps:
                y = f(x)
                if y not in S:
                    S.add(y)
                    new.add(y)
        frontier = new
        if len(S) == size:
            break
    return frozenset(S)


def green(n):
    elems, mul, left, right, G = build(n)
    N = len(elems)
    gens = [0] * N  # placeholder; generators are identified below

    # generators: the elements of Coxeter length 1
    def length(w):
        return sum(1 for i in range(n) for j in range(i + 1, n) if w[i] > w[j])
    gs = [k for k, w in enumerate(elems) if length(w) == 1]

    jm = [(lambda i: (lambda x: mul(x, i)))(g) for g in gs] + \
         [(lambda i: (lambda x: mul(i, x)))(g) for g in gs]
    lm = [(lambda i: (lambda x: mul(i, x)))(g) for g in gs]
    rm = [(lambda i: (lambda x: mul(x, i)))(g) for g in gs]

    J = [closure(k, jm, N) for k in range(N)]
    L = [closure(k, lm, N) for k in range(N)]
    R = [closure(k, rm, N) for k in range(N)]
    return N, len(set(J)), len(set(L)), len(set(R)), J, elems, mul


# ------------------------------------------ partitions and hook lengths ------

def partition_number(n):
    p = [0] * (n + 1)
    p[0] = 1
    for k in range(1, n + 1):
        total, j = 0, 1
        while True:
            g1 = k - j * (3 * j - 1) // 2
            g2 = k - j * (3 * j + 1) // 2
            if g1 < 0 and g2 < 0:
                break
            sign = 1 if (j - 1) % 2 == 0 else -1
            if g1 >= 0:
                total += sign * p[g1]
            if g2 >= 0:
                total += sign * p[g2]
            j += 1
        p[k] = total
    return p[n]


def partitions(n, mx=None):
    if mx is None:
        mx = n
    if n == 0:
        yield ()
        return
    for k in range(min(n, mx), 0, -1):
        for rest in partitions(n - k, k):
            yield (k,) + rest


def distinct_hook_lengths(lam):
    m = len(lam)
    seen = set()
    for i in range(m):
        for j in range(lam[i]):
            right = lam[i] - j - 1
            below = sum(1 for r in range(i + 1, m) if lam[r] > j)
            seen.add(right + below + 1)
    return len(seen)


# ------------------------------------------------------------------ main -----

def main():
    print("=" * 68)
    print("0-Hecke monoid H_n(0): Green's classes vs. partitions")
    print("=" * 68)

    print("\n[1] Self-checks on the multiplication")
    print("    n |  |H|  associativity violations | idempotents | 2^(n-1)")
    for n in range(2, 6):
        elems, mul, left, right, G = build(n)
        N = len(elems)
        bad = 0
        for a in range(N):
            for b in range(N):
                ab = mul(a, b)
                for c in range(N):
                    if mul(ab, c) != mul(a, mul(b, c)):
                        bad += 1
        idem = sum(1 for k in range(N) if mul(k, k) == k)
        print("    {} |  {:3d}  {:22d} | {:10d} | {:7d}".format(
            n, N, bad, idem, 2 ** (n - 1)))

    print("\n[2] Green's classes versus the conjectured values")
    print("    n | J-classes | L-classes | R-classes | p(n) | sum_lambda #hook")
    for n in range(2, 6):
        N, nJ, nL, nR, J, elems, mul = green(n)
        s = sum(distinct_hook_lengths(l) for l in partitions(n))
        print("    {} | {:9d} | {:9d} | {:9d} | {:4d} | {:19d}".format(
            n, nJ, nL, nR, partition_number(n), s))
    print("\n    -> the number of two-sided classes is n!, not p(n):")
    print("       at n = 3 we get 6, while p(3) = 3.   (first half fails)")
    print("       at n = 2 we get 2 = p(2), a coincidence.")
    print("    -> the number of left classes is n!, not the hook-length sum:")
    print("       at n = 3 we get 6, while the sum is 8.  (second half fails)")

    print("\n[3] The six principal two-sided ideals of H_3(0)")
    N, nJ, nL, nR, J, elems, mul = green(3)
    for k in range(N):
        vec = [1 if m in J[k] else 0 for m in range(N)]
        print("    pi_{:<12s} J-ideal = {}   size {}".format(
            "".join(str(x + 1) for x in elems[k]), vec, len(J[k])))
    print("    all six characteristic vectors are distinct -> 6 J-classes")

    print("\n[4] Partitions of 3 and their distinct hook lengths")
    for lam in partitions(3):
        print("    lambda = {:<10s} # distinct hook lengths = {}".format(
            str(lam), distinct_hook_lengths(lam)))
    print("    sum = {}".format(sum(distinct_hook_lengths(l)
                                   for l in partitions(3))))

    print("\n" + "=" * 68)
    print("CONCLUSION: 6 != 3 (two-sided classes) and 6 != 8 (left classes).")
    print("Conjecture 00000003843 is false.")
    print("=" * 68)


if __name__ == "__main__":
    main()
