/-
  Disproof of conjecture `00000002308`.

  Conjecture (as filed):
    Definition: A complete group satisfies G = Aut(G).
    Conjecture: The order of the smallest nontrivial solvable complete group is
                2^{11}·3 (an explicit discovery); its structure is a minimal
                example of a semidirect product of a 2-group.

  The conjecture is FALSE.  Under the standard meaning of "complete" (trivial
  center and every automorphism is inner, equivalently G ≅ Aut(G) via
  conjugation), the symmetric group S_3 is a witness:

    * |S_3| = 6;
    * Z(S_3) = {e},  so S_3 is centerless;
    * every automorphism of S_3 is inner and |Aut(S_3)| = |Inn(S_3)| = 6,
      so S_3 ≅ Aut(S_3);
    * S_3 is solvable: A_3 ◁ S_3 with A_3 abelian and index 2;
    * S_3 = C_3 ⋊ C_2 is a semidirect product with normal C_3 = A_3;
    * 6 < 2^{11}·3 = 6144.

  Moreover every group of order 2, 3, 4, 5 is abelian, so no group of those
  orders can be complete (its center is the whole group, hence non-trivial).
  Therefore 6 is the least order of a non-trivial solvable complete group,
  contradicting the claimed 2^{11}·3.

  This file uses core Lean only (`import Std`, no Mathlib, no `sorry`).

  PERFORMANCE.  Naively enumerating all 6^6 = 46656 functions Fin 6 → Fin 6 and
  filtering for homomorphisms is correct but slow (~4m45s).  Here we use the
  generator-based reduction: S_3 is generated by a transposition `tau` and a
  3-cycle `sigma` (the six words 1, tau, sigma, sigma^2, tau*sigma,
  tau*sigma^2 hit all six elements, checked by `generators_generate`).  A group
  homomorphism out of S_3 is determined by the images (u,v) of (tau,sigma), and
  every pair of images extends via the fixed word decomposition to a candidate
  map `mkHom u v`.  Enumerating the 6×6 = 36 pairs and keeping those that are
  homomorphisms and bijections yields |End(S_3)| = 10 and |Aut(S_3)| = 6.
-/

import Std
set_option maxRecDepth 2000000
set_option maxHeartbeats 20000000

namespace Tlmc2308

/-! ## A concrete model of S_3 on `Fin 6`

Index convention (matching the enumeration of `permutations(range(3))`):
`0 = id`, `1 = (12)`, `2 = (01)`, `3 = (012)`, `4 = (021)`, `5 = (02)`. -/

/-- Multiplication table of S_3 (`mul i j` = `i` after `j`). -/
def mul : Fin 6 → Fin 6 → Fin 6
  | ⟨0, _⟩, ⟨0, _⟩ => ⟨0, by decide⟩
  | ⟨0, _⟩, ⟨1, _⟩ => ⟨1, by decide⟩
  | ⟨0, _⟩, ⟨2, _⟩ => ⟨2, by decide⟩
  | ⟨0, _⟩, ⟨3, _⟩ => ⟨3, by decide⟩
  | ⟨0, _⟩, ⟨4, _⟩ => ⟨4, by decide⟩
  | ⟨0, _⟩, ⟨5, _⟩ => ⟨5, by decide⟩
  | ⟨1, _⟩, ⟨0, _⟩ => ⟨1, by decide⟩
  | ⟨1, _⟩, ⟨1, _⟩ => ⟨0, by decide⟩
  | ⟨1, _⟩, ⟨2, _⟩ => ⟨4, by decide⟩
  | ⟨1, _⟩, ⟨3, _⟩ => ⟨5, by decide⟩
  | ⟨1, _⟩, ⟨4, _⟩ => ⟨2, by decide⟩
  | ⟨1, _⟩, ⟨5, _⟩ => ⟨3, by decide⟩
  | ⟨2, _⟩, ⟨0, _⟩ => ⟨2, by decide⟩
  | ⟨2, _⟩, ⟨1, _⟩ => ⟨3, by decide⟩
  | ⟨2, _⟩, ⟨2, _⟩ => ⟨0, by decide⟩
  | ⟨2, _⟩, ⟨3, _⟩ => ⟨1, by decide⟩
  | ⟨2, _⟩, ⟨4, _⟩ => ⟨5, by decide⟩
  | ⟨2, _⟩, ⟨5, _⟩ => ⟨4, by decide⟩
  | ⟨3, _⟩, ⟨0, _⟩ => ⟨3, by decide⟩
  | ⟨3, _⟩, ⟨1, _⟩ => ⟨2, by decide⟩
  | ⟨3, _⟩, ⟨2, _⟩ => ⟨5, by decide⟩
  | ⟨3, _⟩, ⟨3, _⟩ => ⟨4, by decide⟩
  | ⟨3, _⟩, ⟨4, _⟩ => ⟨0, by decide⟩
  | ⟨3, _⟩, ⟨5, _⟩ => ⟨1, by decide⟩
  | ⟨4, _⟩, ⟨0, _⟩ => ⟨4, by decide⟩
  | ⟨4, _⟩, ⟨1, _⟩ => ⟨5, by decide⟩
  | ⟨4, _⟩, ⟨2, _⟩ => ⟨1, by decide⟩
  | ⟨4, _⟩, ⟨3, _⟩ => ⟨0, by decide⟩
  | ⟨4, _⟩, ⟨4, _⟩ => ⟨3, by decide⟩
  | ⟨4, _⟩, ⟨5, _⟩ => ⟨2, by decide⟩
  | ⟨5, _⟩, ⟨0, _⟩ => ⟨5, by decide⟩
  | ⟨5, _⟩, ⟨1, _⟩ => ⟨4, by decide⟩
  | ⟨5, _⟩, ⟨2, _⟩ => ⟨3, by decide⟩
  | ⟨5, _⟩, ⟨3, _⟩ => ⟨2, by decide⟩
  | ⟨5, _⟩, ⟨4, _⟩ => ⟨1, by decide⟩
  | ⟨5, _⟩, ⟨5, _⟩ => ⟨0, by decide⟩

/-- Inverses in S_3. -/
def inv : Fin 6 → Fin 6
  | ⟨0, _⟩ => ⟨0, by decide⟩
  | ⟨1, _⟩ => ⟨1, by decide⟩
  | ⟨2, _⟩ => ⟨2, by decide⟩
  | ⟨3, _⟩ => ⟨4, by decide⟩
  | ⟨4, _⟩ => ⟨3, by decide⟩
  | ⟨5, _⟩ => ⟨5, by decide⟩
  | _ => ⟨0, by decide⟩

/-- The identity element. -/
def e : Fin 6 := ⟨0, by decide⟩

theorem inv_left : ∀ a : Fin 6, mul (inv a) a = e := by decide

/-! ## Generators -/

/-- A transposition, `(01)`. -/
def tau : Fin 6 := ⟨2, by decide⟩

/-- A 3-cycle, `(012)`. -/
def sigma : Fin 6 := ⟨3, by decide⟩

/-- The six canonical words in `tau` and `sigma`:
`1, tau*sigma, tau, sigma, sigma^2, tau*sigma^2`.  These are exactly the six
elements of S_3, so `{tau,sigma}` generates S_3. -/
def genClosure : List (Fin 6) :=
  [e, mul tau sigma, tau, sigma, mul sigma sigma, mul tau (mul sigma sigma)]

/-- Membership test for a `Fin 6` in a list of `Fin 6`. -/
def inList (x : Fin 6) (L : List (Fin 6)) : Bool := L.any (fun y => x == y)

/-- Every word in the two generators is an element of S_3. -/
theorem genClosure_subset :
    genClosure.all (fun x => inList x (List.finRange 6)) = true := by decide

/-- Every element of S_3 is one of the six words.  Together with
`genClosure_subset` this says `{tau,sigma}` generates S_3. -/
theorem generators_generate :
    (List.finRange 6).all (fun x => inList x genClosure) = true := by decide

/-! ## The generator-based candidate maps

A homomorphism out of S_3 is determined by the images `u = f tau`, `v = f sigma`
of the generators.  Reading the canonical words of the six elements, the map is
forced to be
`mkHom u v = [1, u*v, u, v, v*v, u*(v*v)]`
on the indices `0,1,2,3,4,5`. -/

/-- The candidate map determined by the images `u` of `tau` and `v` of `sigma`. -/
def mkHom (u v : Fin 6) : Fin 6 → Fin 6
  | ⟨0, _⟩ => e
  | ⟨1, _⟩ => mul u v
  | ⟨2, _⟩ => u
  | ⟨3, _⟩ => v
  | ⟨4, _⟩ => mul v v
  | ⟨5, _⟩ => mul u (mul v v)
  | _ => e

/-- The 6×6 = 36 candidate maps, one for each pair of generator images. -/
def candidates : List (Fin 6 → Fin 6) :=
  (List.finRange 6).flatMap (fun u =>
    (List.finRange 6).map (fun v => mkHom u v))

/-- `f` respects the multiplication table. -/
def isHom (f : Fin 6 → Fin 6) : Bool :=
  (List.finRange 6).all (fun x =>
    (List.finRange 6).all (fun y => f (mul x y) == mul (f x) (f y)))

/-- `f` is injective, checked on all pairs. -/
def isInj (f : Fin 6 → Fin 6) : Bool :=
  (List.finRange 6).all (fun x =>
    (List.finRange 6).all (fun y => (f x == f y) == (x == y)))

/-- `f` is an automorphism (a bijective homomorphism; injectivity suffices on a
finite set of the same cardinality). -/
def isAut (f : Fin 6 → Fin 6) : Bool := isHom f && isInj f

/-! ## Conjugations (inner automorphisms) -/

/-- Conjugation by `g`: `x ↦ g x g⁻¹`. -/
def conj (g : Fin 6) (x : Fin 6) : Fin 6 := mul (mul g x) (inv g)

/-- The list of the six conjugations. -/
def InnList : List (Fin 6 → Fin 6) := (List.finRange 6).map conj

/-- Pointwise equality of functions `Fin 6 → Fin 6`.  (There is no `DecidableEq`
instance for the function space in core Lean, so we hand-roll one returning
`Bool`.) -/
def feq (f g : Fin 6 → Fin 6) : Bool :=
  (List.finRange 6).all (fun x => f x == g x)

/-- Membership of a function in a list, up to `feq`. -/
def mem (f : Fin 6 → Fin 6) (L : List (Fin 6 → Fin 6)) : Bool :=
  L.any (fun g => feq f g)

/-! ## The verification -/

/-- `S_3` has six elements. -/
theorem card_S3 : (List.finRange 6).length = 6 := by decide

/-- The center of S_3 is trivial: the only central element is the identity. -/
theorem center_trivial :
    ((List.finRange 6).filter (fun z =>
      (List.finRange 6).all (fun a => mul z a == mul a z))).map
        (fun z => z.val) = [0] := by decide

/-- The six conjugations are pairwise distinct. -/
theorem inn_injective :
    (List.finRange 6).all (fun g =>
      (List.finRange 6).all (fun h => feq (conj g) (conj h) == (g == h))) = true := by
  decide

/-- There are six inner automorphisms, so `|Inn(S_3)| = 6`. -/
theorem card_inn : InnList.length = 6 := by decide

/-- The generator-based enumeration finds exactly 10 endomorphisms of S_3
(1 trivial, 3 with image of order 2, 6 automorphisms). -/
theorem card_hom : (candidates.filter isHom).length = 10 := by decide

/-- **`|Aut(S_3)| = 6`**, by the generator-based enumeration. -/
theorem card_aut : (candidates.filter isAut).length = 6 := by decide

/-- Every inner automorphism is an automorphism. -/
theorem inn_le_aut : InnList.all isAut = true := by decide

/-- **`Aut(S_3) = Inn(S_3)`**: every automorphism is inner.  Combined with
`inn_le_aut`, `card_aut = 6` and `card_inn = 6`, this identifies the two sets. -/
theorem aut_eq_inn : (candidates.filter isAut).all (fun f => mem f InnList) = true := by
  decide

/-! ## Solvability and the semidirect-product structure -/

/-- `A_3 = {1, sigma, sigma^2}`, a normal subgroup of index 2. -/
def A3 : List (Fin 6) := [e, sigma, mul sigma sigma]

/-- `A_3` is abelian. -/
def A3Abelian : Bool := A3.all (fun a => A3.all (fun b => mul a b == mul b a))

/-- `A_3` is normal in S_3. -/
def A3Normal : Bool :=
  (List.finRange 6).all (fun g => A3.all (fun a => inList (conj g a) A3))

/-- A complement of order 2: `T = {1, tau}`. -/
def T2 : List (Fin 6) := [e, tau]

/-- The set of products `a * t` with `a ∈ A_3`, `t ∈ T2`. -/
def A3T2 : List (Fin 6) := A3.flatMap (fun a => T2.map (fun t => mul a t))

theorem A3_abelian : A3Abelian = true := by decide

theorem A3_normal : A3Normal = true := by decide

/-- `A_3` has index 2 in S_3: `|S_3| = 2·|A_3|`. -/
theorem A3_index2 : A3.length * 2 = (List.finRange 6).length := by decide

/-- `A_3` and `T2` intersect trivially. -/
theorem A3_inter_T2 :
    (A3.filter (fun a => inList a T2)).map (fun a => a.val) = [0] := by decide

/-- `A_3·T2 = S_3`: every element is uniquely `a*t`.  This is the internal
semidirect-product decomposition `S_3 = A_3 ⋊ T2`. -/
theorem A3T2_eq_S3 :
    A3T2.all (fun x => inList x (List.finRange 6)) = true
    ∧ (List.finRange 6).all (fun x => inList x A3T2) = true := by decide

/-- `tau` has order 2, so `T2 ≅ C_2`. -/
theorem tau_order_two : (mul tau tau == e) = true := by decide

/-- `sigma` has order 3, so `A_3 ≅ C_3`; `T2 ≅ C_2` acts on it by inversion
(the action is non-trivial, since `S_3` is non-abelian). -/
theorem sigma_order_three : (mul sigma (mul sigma sigma) == e) = true := by decide

/-- **Solvability data for S_3**: `A_3` is abelian and normal of index 2; the
quotient `S_3/A_3 ≅ C_2` is abelian.  Hence the derived series
`S_3 ▷ A_3 ▷ 1` has abelian factors and S_3 is solvable. -/
theorem solvable_S3 :
    (A3Abelian && A3Normal) = true
    ∧ A3.length * 2 = (List.finRange 6).length := by
  exact ⟨by decide, by decide⟩

/-! ## The order bound and the collected refutation -/

/-- The claimed order `2^{11}·3 = 6144` is strictly larger than `6`. -/
theorem six_lt_6144 : 6 < 2 ^ 11 * 3 := by decide

/-- **Conjecture `00000002308` is FALSE.**

The conjunction records: `Z(S_3) = {e}` (trivial center), `|Inn(S_3)| = 6`,
`|Aut(S_3)| = 6` with `Aut(S_3) = Inn(S_3)` (so S_3 is complete), solvability
via the abelian normal `A_3` of index 2, and `6 < 2^{11}·3`.  Thus the smallest
non-trivial solvable complete group has order `6`, not `2^{11}·3 = 6144`. -/
theorem conjecture_00000002308_false :
    ((List.finRange 6).filter (fun z =>
      (List.finRange 6).all (fun a => mul z a == mul a z))).map
        (fun z => z.val) = [0]
    ∧ InnList.length = 6
    ∧ (candidates.filter isAut).length = 6
    ∧ (candidates.filter isAut).all (fun f => mem f InnList) = true
    ∧ (A3Abelian && A3Normal) = true
    ∧ A3.length * 2 = (List.finRange 6).length
    ∧ 6 < 2 ^ 11 * 3 := by
  exact ⟨center_trivial, card_inn, card_aut, aut_eq_inn,
    (solvable_S3).1, (solvable_S3).2, six_lt_6144⟩

end Tlmc2308
